export interface TimezoneOption {
  value: string;
  label: string;
}

export const TIMEZONES: TimezoneOption[] = [
  { value: 'UTC', label: 'UTC - Coordinated Universal Time' },
  { value: 'America/New_York', label: 'America/New_York - Eastern Time' },
  { value: 'America/Chicago', label: 'America/Chicago - Central Time' },
  { value: 'America/Denver', label: 'America/Denver - Mountain Time' },
  { value: 'America/Phoenix', label: 'America/Phoenix - Arizona (no DST)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles - Pacific Time' },
  { value: 'America/Anchorage', label: 'America/Anchorage - Alaska Time' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu - Hawaii Time' },
  { value: 'America/St_Johns', label: 'America/St_Johns - Newfoundland Time' },
  { value: 'America/Halifax', label: 'America/Halifax - Atlantic Time' },
  { value: 'America/Toronto', label: 'America/Toronto - Eastern Time' },
  { value: 'America/Winnipeg', label: 'America/Winnipeg - Central Time' },
  { value: 'America/Edmonton', label: 'America/Edmonton - Mountain Time' },
  { value: 'America/Vancouver', label: 'America/Vancouver - Pacific Time' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City - Central Mexico' },
  { value: 'America/Bogota', label: 'America/Bogota - Colombia' },
  { value: 'America/Lima', label: 'America/Lima - Peru' },
  { value: 'America/Santiago', label: 'America/Santiago - Chile' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo - Brazil' },
  { value: 'America/Argentina/Buenos_Aires', label: 'America/Argentina/Buenos_Aires - Argentina' },
  { value: 'Europe/London', label: 'Europe/London - UK' },
  { value: 'Europe/Paris', label: 'Europe/Paris - France' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin - Germany' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid - Spain' },
  { value: 'Europe/Rome', label: 'Europe/Rome - Italy' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam - Netherlands' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw - Poland' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm - Sweden' },
  { value: 'Europe/Athens', label: 'Europe/Athens - Greece' },
  { value: 'Europe/Helsinki', label: 'Europe/Helsinki - Finland' },
  { value: 'Europe/Istanbul', label: 'Europe/Istanbul - Turkey' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow - Russia' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo - Egypt' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg - South Africa' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos - Nigeria' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai - UAE' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata - India' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok - Thailand' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore - Singapore' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong - Hong Kong' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai - China' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo - Japan' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul - South Korea' },
  { value: 'Australia/Perth', label: 'Australia/Perth - Western Australia' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney - New South Wales' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne - Victoria' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland - New Zealand' },
];

export const USER_TIMEZONES: TimezoneOption[] = [
  { value: '', label: 'Hidden - Do not display timezone' },
  ...TIMEZONES,
];
